name: validation
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - jupyter
  - ipykernel
  - numpy
  - pandas
  - geopandas
  - xarray
  - rioxarray
  - shapely
  - scipy
  - scikit-image
  - matplotlib
  - seaborn
  - tqdm
  - pyarrow
  - bottleneck
  - cftime
  - dask 
  - netCDF4
  - pip:
    - metloom
    - uavsar_pytools
    - phase_o_matic